<?php
 class MySQLConnection
    {
        var $connection=null;
        var $server="localhost";
        var $username="root";
        var $password="";
        var $database="dbavigabso";
        /*var $server="208.43.69.173";
        var $username="ssocial";
        var $password="s!@#4";
        var $database="ssocial";*/
	/*var $server="localhost";
        var $username="aminhosp_viral";
        var $password="avigabso";
        var $database="aminhosp_dbavigabso";*/
        var $result=null;

        /**
         * This method is used to Open Connection to Database
         */
        function Open()
        {
            $this->connection=mysql_connect($this->server, $this->username,$this->password,false,65536);
            mysql_select_db($this->database,$this->connection) or die("Error:".mysql_error());
        }

        /**
         * This method is used to Close Connection to Database
         */
        function Close()
        {
            mysql_close($this->connection);
        }

        /**
         * This method is used to Insert Record in to Respective Table
         * @param string $query
         * @return boolean true on Success otherwise false
         */
        function InsertQuery($query)
        {
            $this->result=mysql_query($query,$this->connection);
            if( mysql_affected_rows()>0)
                return true;
            else
                return false;
        }

        /**
         * This method is used to Update Record of Respective Table
         * @param  string $query Update Query
         * @return boolean true on Success otherwise false
         */
        function UpdateQuery($query)
        {
            if( mysql_query($query,$this->connection))
                return true;
            else
                return false;
        }

        /**
         * This method is used to Delete Record from Respective Table
         * @param string $query
         * @return boolean true on Success otherwise false
         */
        function DeleteQuery($query)
        {
            $this->result=mysql_query($query,$this->connection);
            if( mysql_affected_rows()>0)
                return true;
            else
                return false;
        }

        /**
         * This method is used to Return Records by Query
         * @param string $query
         * @return MySqlResult $result Returns MySql Resultset
         */
        function SelectQuery($query)
        {
            $this->result=mysql_query($query,$this->connection);            
            return $this->result;
            //mysql_free_result($this->result);
        }

        /**
         * This method is used to Return Number of Rows Returned
         * @param MySqlResult $result
         * @return int totalrows Returns total number of rows
         */
        function RowsCount($result)
        {
            return mysql_num_rows($result);
        }

        /**
         * This method is used to Return a Record Set in form of an Array
         * @param MySqlResult $result
         * @return array resultSet Return an Array or Records
         */
        function RecordSet($result)
        {
            $this->resultSet=array();

            while($row=  mysql_fetch_assoc($result))
            {
                array_push($this->resultSet, $row);
            }
            return $this->resultSet;
        }

        /**
         * This method is used to Return an Last ID Generated by Last Inserterd Query
         * @return int Last ID generated ID from Table
         */
        function GetLastInsertedId()
        {
            return mysql_insert_id();
        }
  }

 ?>